
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookify-client
spec:
  selector:
    matchLabels:
      app: bookify-client
  replicas: 2
  template:
    metadata:
      labels:
        app: bookify-client
    spec:
      containers:
      - name: bookify-client
        image: nayem9b/bookify-client-github-build:1.0.2
        # volumeMounts:
        #   - name: config-volume
        #     mountPath: /opt/config
        env:
        - name: REACT_APP_API_KEY
          valueFrom:
            secretKeyRef:
              name: bookify-client-secret
              key: REACT_APP_API_KEY
        - name: REACT_APP_AUTH_DOMAIN
          valueFrom:
            secretKeyRef:
              name: bookify-client-secret
              key: REACT_APP_AUTH_DOMAIN
        - name: REACT_APP_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: bookify-client-secret
              key: REACT_APP_PROJECT_ID 
        - name: REACT_APP_STORAGE_BUCKET
          valueFrom:
            secretKeyRef:
              name: bookify-client-secret
              key: REACT_APP_STORAGE_BUCKET 
        - name: REACT_APP_MESSAGING_SENDER_ID
          valueFrom:
            secretKeyRef:
              name: bookify-client-secret
              key: REACT_APP_MESSAGING_SENDER_ID 
        - name: REACT_APP_APP_ID
          valueFrom:
            secretKeyRef:
              name: bookify-client-secret
              key: REACT_APP_APP_ID 
        - name: REACT_APP_IMG_BB_KEY
          valueFrom:
            secretKeyRef:
              name: bookify-client-secret
              key: REACT_APP_IMG_BB_KEY 
        imagePullPolicy: Always
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 3000
        #   initialDelaySeconds: 10
        #   periodSeconds: 10
        #   timeoutSeconds: 2
        #   failureThreshold: 3
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 3000
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
        #   timeoutSeconds: 2
        #   failureThreshold: 3
        ports:
        - containerPort: 3000
      # volumes:
      # - name: config-volume
      #   configMap:
      #     name: bookify-config
