apiVersion: v1
kind: Service
metadata:
  name: sheba-frontend-service
  namespace: sheba
spec:
  type: LoadBalancer
  selector:
    app: sheba-frontend
  ports:
    - port: 80           
      targetPort: 5000   
      nodePort: 32080    
      protocol: TCP
      name: http


---
apiVersion: v1
kind: Service
metadata:
  name: sheba-backend
  namespace: sheba
spec:
  type: LoadBalancer
  selector:
    app: sheba-backend
  ports:
    - name: http-3000
      port: 3000
      targetPort: 3000
      protocol: TCP

