apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookify-backend
spec:
  replicas: 2  # Standard replicas for staging
  template:
    spec:
      containers:
      - name: bookify-backend
        env:
        - name: ENV
          value: "staging"
        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "200m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "400m"