apiVersion: apps/v1
kind: Deployment
metadata:
  name: sheba-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sheba-backend
  template:
    metadata:
      labels:
        app: sheba-backend
    spec:
      containers:
        - name: sheba-backend
          image: nayem9b/sheba-backend-github-build:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
            - containerPort: 4000
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: sheba-backend-config
                  key: NODE_ENV 
            - name: PORT 
              valueFrom:
                configMapKeyRef:
                  name: sheba-backend-config
                  key: PORT
            - name: JWT_ACCESS_EXPIRES_IN
              valueFrom:
                configMapKeyRef:
                  name: sheba-backend-config
                  key: JWT_ACCESS_EXPIRES_IN
            - name: JWT_REFRESH_EXPIRES_IN
              valueFrom:
                configMapKeyRef:
                  name: sheba-backend-config
                  key: JWT_REFRESH_EXPIRES_IN
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: sheba-backend-secret
                  key: DATABASE_URL
            - name: BCRYPT_SALT_ROUNDS
              valueFrom:
                secretKeyRef:
                  name: sheba-backend-secret
                  key: BCRYPT_SALT_ROUNDS
            - name: ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: sheba-backend-secret
                  key: ACCESS_SECRET 
            - name: REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: sheba-backend-secret
                  key: REFRESH_SECRET 
            - name: CLERK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: sheba-backend-secret
                  key: CLERK_SECRET_KEY 
            - name: CLERK_PUBLISHABLE_KEY
              valueFrom:
                secretKeyRef:
                  name: sheba-backend-secret
                  key: CLERK_PUBLISHABLE_KEY 
            - name: CLERK_API_VERSION
              valueFrom:
                secretKeyRef:
                  name: sheba-backend-secret
                  key: CLERK_API_URL
            - name: WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: sheba-backend-secret
                  key: WEBHOOK_SECRET
            - name: AWS_ACCESS_ID
              valueFrom:
                secretKeyRef:
                  name: sheba-backend-secret
                  key: AWS_ACCESS_ID 
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: sheba-backend-secret
                  key: AWS_ACCESS_KEY
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: sheba-backend-secret
                  key: REDIS_URL    
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sheba-backend-secret
                  key: JWT_SECRET    
            - name: SSL_BASE_PAYMENT_URL
              valueFrom:
                secretKeyRef:
                  name: sheba-backend-secret
                  key: SSL_BASE_PAYMENT_URL   
            - name: STORE_ID
              valueFrom:
                secretKeyRef:
                  name: sheba-backend-secret
                  key: STORE_ID    
            - name: SSL_BASE_VALIDATION_URL
              valueFrom:
                secretKeyRef:
                  name: sheba-backend-secret
                  key: SSL_BASE_VALIDATION_URL       
            - name: STORE_PASS
              valueFrom:
                secretKeyRef:
                  name: sheba-backend-secret
                  key: STORE_PASS