apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
# - secret.yaml

images:
- name: nayem9b/sheba-backend-github-build
  newName: nayem9b/sheba-backend-github-build
  newTag: PLACEHOLDER_TAG