apiVersion: v1
kind: Service
metadata:
  name: sheba-backend
spec:
  type: LoadBalancer
  selector:
    app: sheba-backend
  ports:
    - name: http-3000
      port: 3000
      targetPort: 3000
      protocol: TCP
